resources:
  - name: srcFrontRepo
    type: GitRepo
    configuration:
      gitProvider: hza_github
      path: HamzaZFrog/k8s-app
      branches:
        include: master
  - name: FrontAppBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory_eu
      buildName: FrontApp_Build
      buildNumber: 1

pipelines:
  - name: k8s_pipeline
    configuration:
      environmentVariables:
        readOnly:
          art_url: "http://artifactory-eu.soleng-emea-staging.jfrog.team/artifactory"
    steps:
      - name: build_front_app
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: docker.bintray.io/jfrog/pipelines-u18node
                tag: 12.14.0
          inputResources:
            - name: srcFrontRepo
          integrations:
            - name: artifactory_eu
            - name: artSecret
        execution:
          onStart:
            - add_run_variables buildStepName=${step_name}
            - add_run_variables ${step_name}_buildNumber=${run_number}
            - add_run_variables ${step_name}_buildName=${pipeline_name}
            - retry_command jfrog rt c myart --url $int_artifactory_eu_url --user $int_artifactory_eu_user --apikey $int_artifactory_eu_apikey --interactive=false
            - jfrog rt c show myart
            - jfrog --version
            - retry_command jfrog rt npmc
            - retry_command jfrog rt npmi --build-name=$step_name --build-number=$run_number
            - retry_command jfrog rt bp $step_name $run_number
            - add_run_files /tmp/jfrog/. jfrog
