resources:
  - name: srcFrontRepo
    type: GitRepo
    configuration:
      gitProvider: hza_github
      path: HamzaZFrog/k8s-app
      branches:
        include: master
  - name: FrontAppBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory_eu
      buildName: FrontApp_Build
      buildNumber: ${run_number}

pipelines:
  - name: k8s_pipeline
    configuration:
      environmentVariables:
        readOnly:
          art_url: "http://artifactory-eu.soleng-emea-staging.jfrog.team/artifactory"
    steps:
      - name: npm_build_frontend
        type: NpmBuild
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: docker.bintray.io/jfrog/pipelines-u18node
                tag: 12.14.0
          repositoryName: npm
          sourceLocation: .
          integrations:
            - name: artifactory_eu
          inputResources:
            - name: srcNpmRepo
        execution:
          onStart:
            - echo  "Preparing for work..."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "You Lose"
          onComplete:
            - echo "Leave it as you found it. Let's clean it"
      
      - name: pack_frontend
        type: Bash
        configuration:
          inputSteps:
            - name: npm_build_frontend
          integrations:
            - name: artifactory_eu
        execution:
          onStart:
            - export tempStateLocation="$step_tmp_dir/npmSourceState"
            - restore_run_files npmBuildInputGitRepo $tempStateLocation
            - pushd $tempStateLocation
            - npm run build
            - add_run_files $tempStateLocation/. npmBuildInputGitRepo
     
      - name: publish_frontend
        type: NpmPublish
        configuration:
          repositoryName: npm-dev-local
          inputSteps:
            - name: pack_frontend
          integrations:
            - name: myArtifactory
        execution:
          onStart:
            - export inputNpmBuildStepName="bld_frontend"