resources:
  - name: srcFrontRepo
    type: GitRepo
    configuration:
      gitProvider: hza_github
      path: HamzaZFrog/k8s-app
      branches:
        include: master

  - name: FrontAppBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory_yannaws
      buildName: FrontApp_Build
      buildNumber: ${run_number}

pipelines:
  - name: k8s_pipeline
    configuration:
      environmentVariables:
        readOnly:
          art_url: "http://artifactory-eu.soleng-emea-staging.jfrog.team/artifactory"
    steps:
      - name: npm_package_frontend
        type: Bash
        configuration:
          inputResources:
            - name: srcFrontRepo
          integrations:
            - name: artifactory_eu
        execution:
          onStart:
            - echo "CLI installation"
            - "curl -fL https://getcli.jfrog.io | sh &&  chmod 755 jfrog"
            - pwd
            - ls -alrt
            - >-
              ./jfrog rt c --interactive=false --url=${int_artifactory_eu_url}
              --user=${int_artifactory_eu_user} --apikey=${int_artifactory_eu_apikey} myart &&
              ./jfrog rt use myart && ./jfrog rt ping
            - >

          onExecute:
            - echo "${res_src_resourcePath}"
            - cd "${res_src_resourcePath}"
            - pwd
            - ls -alrt
            - export "JFROG_CLI_HOME_DIR=$(pwd)"
            - echo $JFROG_CLI_HOME_DIR
            - retry_command $JFROG_CLI_HOME_DIR/jfrog rt npmc --repo-resolve npm --repo-deploy npm --server-id-resolve myart --server-id-deploy myart
            - ls -la
            - retry_command $JFROG_CLI_HOME_DIR/jfrog rt npm-ci --build-name=FrontApp_Build --build-number=${run_number}
            - ls -la
            - retry_command $JFROG_CLI_HOME_DIR/jfrog rt npmp --build-name=FrontApp_Build --build-number=${run_number}
            - ls -la
          onComplete:
            - ls -la

      - name: build_app
        type: Bash
        configuration:
          environmentVariables:
            dockerImageName: artifactory-eu.soleng-emea-staging.jfrog.team/docker-local/frontapp
            dockerImageTag: ${run_number}
          inputResources:
            - name: srcFrontRepo
          inputSteps:
            - name: npm_package_frontend
          integrations:
            - name: artifactory_eu
        execution:
          onStart:
            - restore_run_files packaged_npm .
            - ls
            - retry_command jfrog rt c myart --url $int_artifactory_eu_url --user $int_artifactory_eu_user --apikey $int_artifactory_eu_apikey --interactive=false
            - retry_command jfrog rt ping
            - add_run_variables buildStepName=${step_name}
            - add_run_variables ${step_name}_buildNumber=${run_number}
            - add_run_variables ${step_name}_buildName=${pipeline_name}
            - ls
            - cd $res_src_resourcePath
            - docker build --pull --no-cache -t $dockerImageName:$dockerImageTag --build-arg REGISTRY=${int_artifactory_eu_url} .
            - jfrog rt bce $pipeline_name $run_number
            - jfrog rt docker-push artifactory-eu.soleng-emea-staging.jfrog.team/docker-local/app:$run_number docker-local --build-name=$pipeline_name --build-number=$run_number

