resources:
  - name: srcFrontRepo
    type: GitRepo
    configuration:
      gitProvider: hza_github
      path: HamzaZFrog/k8s-app
      branches:
        include: master
  - name: FrontAppBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory_eu
      buildName: FrontApp_Build
      buildNumber: ${run_number}

pipelines:
  - name: k8s_pipeline
    configuration:
      environmentVariables:
        readOnly:
          art_url: "http://artifactory-eu.soleng-emea-staging.jfrog.team/artifactory"
    steps:
      - name: npm_build_frontend
        type: NpmBuild
        configuration:
          repositoryName: npm
          sourceLocation: front/
          integrations:
            - name: artifactory_eu
          inputResources:
            - name: srcFrontRepo

      - name: npm_package_frontend
        type: Bash
        configuration:
          inputSteps:
            - name: npm_build_frontend
          integrations:
            - name: artifactory_eu
        execution:
          onStart:
            - ls -la
            - restore_run_files npm_build_frontend_sourceStateName .
            - cd front
            - ls -la
            - npm run build                   
          onComplete:
            - ls -la
            - cd ..
            - add_run_files . npm_package_frontend_sourceStateName    
            - ls -la

      - name: publish_frontend
        type: NpmPublish
        configuration:
          environmentVariables:
            inputNpmBuildStepName: npm_build_frontend
          repositoryName: npm-dev-local
          inputSteps:
            - name: npm_package_frontend
          integrations:
            - name: artifactory_eu 
        execution:
          onStart:
            - export inputNpmBuildStepName="npm_build_frontend"
            - restore_run_files npm_build_frontend_sourceStateName .     