resources:
  - name: srcFrontRepo
    type: GitRepo
    configuration:
      gitProvider: hza_github
      path: HamzaZFrog/k8s-app/front
      branches:
        include: master
  - name: FrontAppBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory_eu
      buildName: FrontApp_Build
      buildNumber: 1

pipelines:
  - name: k8s_pipeline
configuration:
  environmentVariables:
    readOnly:
      art_url: "http://artifactory-eu.soleng-emea-staging.jfrog.team/artifactory"
  steps:
    - name: build_front_app
      type: Bash
      configuration:
        inputResources:
          - name: srcFrontRepo
        integrations:
          - name: artifactory_eu
          - name: artSecret
      execution:
        onStart:
          - rm -rf $run_dir/workspace/jfrog
          - add_run_variables buildStepName=${step_name}
          - add_run_variables ${step_name}_buildNumber=${run_number}
          - add_run_variables ${step_name}_buildName=${pipeline_name}
          - rm -rf $run_dir/workspace/jfrog
          - retry_command jfrog rt config --url $artifactory_eu _url --user $artifactory_eu _user --apikey $artifactory_eu _apikey --interactive=false
          - retry_command jfrog rt npmc --repo-resolve npm-remote
          - retry_command jfrog rt npmi --build-name=$step_name --build-number=$run_number
          - retry_command jfrog rt bp $step_name $run_number
          - add_run_files /tmp/jfrog/. jfrog
