pipelines:
  - name: backapp_go_pipeline
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: go
            versions:
              - "1.13.7"
    steps:
      # Build the Go app from the GitRepo
      - name: build_go_backapp
        type: GoBuild
        configuration:
          sourceLocation: back/
          repository: app-go
          outputLocation: /tmp/dist
          outputFile: backend
          inputResources:
            - name: src_code_backapp
          integrations:
            - name: artifactory_eu

      # Run some test
      - name: unit_test_go_backapp
        type: Bash
        configuration:
          inputSteps:
            - name: build_go_backapp 
        execution:
          onExecute:
            - echo "Testing ..." 
          onSuccess:
            - echo "OK" 

      # Publish the Go app binary to Artifactory
      - name: publish_go_backapp
        type: GoPublishBinary
        configuration:
          autoPublishBuildInfo: true
          targetRepository: app-generic-dev-local
          inputSteps:
            - name: unit_test_go_backapp
          integrations:
            - name: artifactory_eu
          outputResources:
            - name: build_info_backapp

      - name: scan_go_backapp
        type: XrayScan
        configuration:
          failOnScan: false
          inputResources:
            - name: build_info_backapp
              trigger: false
          outputResources:
            - name: build_info_backapp_scanned
 
        execution:
          onStart:
            - echo "Preparing for work..."
            - echo "Prepping build environment"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"