localRepositories:   
  kaizoku-grdl-dev-local:
    type: gradle
    repoLayout: maven-2-default 
    xray:   
      enabled: true
  kaizoku-grdl-rc-local:
    type: gradle
    repoLayout: maven-2-default 
    xray:   
      enabled: true
  kaizoku-docker-dev-local:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    xray:   
      enabled: true
  kaizoku-docker-rc-local:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    xray:   
      enabled: true
  kaizoku-docker-release-local:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    xray:   
      enabled: true
  kaivengers-helm-dev-local:
    type: helm
    repoLayout: simple-default 
    xray:   
      enabled: false
  kaivengers-docker-release-local:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    xray:   
      enabled: true
remoteRepositories: 
  kaizoku-jcenter-grdl-remote:
    type: gradle 
    repoLayout: maven-2-default 
    url: https://jcenter.bintray.com 
    xray:   
      enabled: true
  kaizoku-dockerhub-remote:
    type: docker 
    url: https://registry-1.docker.io/
    dockerApiVersion: V2
    repoLayout: simple-default 
    enableTokenAuthentication: true
    xray:   
      enabled: true
  kaizoku-bintray-remote:
    type: docker
    url: https://docker.bintray.io/
    dockerApiVersion: V2
    repoLayout: simple-default 
    enableTokenAuthentication: true
    xray:   
      enabled: true
  kaivengers-chartcenter-remote:
    type: helm
    url: https://repo.chartcenter.io/
    repoLayout: simple-default 
    xray:   
      enabled: false
virtualRepositories: 
  kaizoku-docker:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    repositories:   
      - kaizoku-docker-dev-local
      - kaizoku-docker-rc-local
      - kaizoku-docker-release-local
      - kaizoku-dockerhub-remote
      - kaizoku-bintray-remote
      - kaivengers-docker-release-local
    defaultDeploymentRepo: kaizoku-docker-dev-local
  kaizoku-grdl:
    type: gradle
    repoLayout: maven-2-default 
    repositories:   
      - kaizoku-grdl-dev-local
      - kaizoku-grdl-rc-local
      - kaizoku-jcenter-grdl-remote
    defaultDeploymentRepo: kaizoku-grdl-dev-local