localRepositories:   
  jupiter-grdl-dev-local:
    type: gradle
    repoLayout: maven-2-default 
    xray:   
      enabled: true
  jupiter-grdl-rc-local:
    type: gradle
    repoLayout: maven-2-default 
    xray:   
      enabled: true
  jupiter-grdl-release-local:
    type: gradle
    repoLayout: maven-2-default 
    xray:   
      enabled: true
  jupiter-docker-dev-local:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    xray:   
      enabled: true
  jupiter-docker-rc-local:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    xray:   
      enabled: true
  jupiter-docker-release-local:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    xray:   
      enabled: true
  # kaivengers-helm-dev-local:
  #   type: helm
  #   repoLayout: simple-default 
  #   xray:   
  #     enabled: false
  # kaivengers-docker-release-local:
  #   type: docker
  #   dockerApiVersion: V2
  #   repoLayout: simple-default 
  #   xray:   
  #     enabled: true
remoteRepositories: 
  jupiter-jcenter-grdl-remote:
    type: gradle 
    repoLayout: maven-2-default 
    url: https://jcenter.bintray.com 
    xray:   
      enabled: true
  jupiter-dockerhub-remote:
    type: docker 
    url: https://registry-1.docker.io/
    dockerApiVersion: V2
    repoLayout: simple-default 
    enableTokenAuthentication: true
    xray:   
      enabled: true
  jupiter-bintray-remote:
    type: docker
    url: https://docker.bintray.io/
    dockerApiVersion: V2
    repoLayout: simple-default 
    enableTokenAuthentication: true
    xray:   
      enabled: true
  saturn-chartcenter-remote:
    type: helm
    url: https://repo.chartcenter.io/
    repoLayout: simple-default 
    xray:   
      enabled: false
virtualRepositories: 
  jupiter-docker:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    repositories:   
      - jupiter-docker-dev-local
      - jupiter-docker-rc-local
      - jupiter-docker-release-local
      - jupiter-dockerhub-remote
      - jupiter-bintray-remote
      - saturn-docker-release-local
    defaultDeploymentRepo: jupiter-docker-dev-local
  jupiter-grdl:
    type: gradle
    repoLayout: maven-2-default 
    repositories:   
      - jupiter-grdl-dev-local
      - jupiter-grdl-rc-local
      - jupiter-grdl-release-local
      - jupiter-jcenter-grdl-remote
    defaultDeploymentRepo: jupiter-grdl-dev-local