localRepositories:   
  avengers-npm-dev-local:
    type: npm
    repoLayout: npm-default 
    xray:   
      enabled: true
  avengers-npm-rc-local:
    type: npm
    repoLayout: npm-default 
    xray:   
      enabled: true
  avengers-generic-dev-local:
    type: generic
    repoLayout: simple-default 
    xray:   
      enabled: true
  avengers-generic-rc-local:
    type: generic
    repoLayout: simple-default 
    xray:   
      enabled: true
  avengers-docker-dev-local:
    type: docker
    repoLayout: simple-default 
    xray:   
      enabled: true
  avengers-docker-rc-local:
    type: docker
    repoLayout: simple-default 
    xray:   
      enabled: true
  avengers-docker-release-local:
    type: docker
    repoLayout: simple-default 
    xray:   
      enabled: true
remoteRepositories: 
  avengers-npmjs-remote:
    type: npm
    repoLayout: npm-default 
    url: https://registry.npmjs.org
    xray:   
      enabled: true
  avengers-dockerhub-remote:
    type: docker 
    url: https://registry-1.docker.io/
    dockerApiVersion: V2
    repoLayout: simple-default 
    enableTokenAuthentication: true
    xray:   
      enabled: true
  avengers-bintray-remote:
    type: docker
    url: https://docker.bintray.io/
    dockerApiVersion: V2
    repoLayout: simple-default 
    enableTokenAuthentication: true
    xray:   
      enabled: true
virtualRepositories: 
  avengers-npm:
    type: npm
    repoLayout: npm-default 
    repositories:   
      - avengers-npm-dev-local
      - avengers-npm-rc-local
      - avengers-npmjs-remote
    defaultDeploymentRepo: avengers-npm-dev-local
  avengers-generic:
    type: generic
    repoLayout: simple-default 
    repositories:   
      - avengers-generic-dev-local
      - avengers-generic-rc-local
    defaultDeploymentRepo: avengers-generic-dev-local
  avengers-docker:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    repositories:   
      - avengers-docker-dev-local
      - avengers-docker-rc-local
      - avengers-docker-release-local
      - avengers-dockerhub-remote
      - avengers-bintray-remote
      - kaivengers-docker-release-local
    defaultDeploymentRepo: avengers-docker-dev-local