resources:
# PROJECT_INIT PIPELINE
  - name: src_dockerfile_base_image_helm
    type: GitRepo
    configuration:
      gitProvider: yann_github
      path: cyan21/k8s-app
      files:
        include: ^chart\/CI\/jfrog\/Dockerfile
      branches:
        include: jfrog-ode 

  - name: bi_base_image_helm 
    type: BuildInfo 
    configuration:
      sourceArtifactory: artifactory_eu
      buildName: helm_base_image
      buildNumber: ${run_number} 

  - name: src_code_k8s_helm
    type: GitRepo
    configuration:
      files:
        include: ^chart\/.+
      gitProvider: yann_github
      path: cyan21/k8s-app
      branches:
        include: jfrog-ode

  - name: hc_my_app
    type: HelmChart
    configuration:
      sourceArtifactory: artifactory_eu
      repository: ${envVarHelmRepo}
      chart: ${envVarHelmName}
      version: ${envVarHelmVers}
      
  - name: bi_hc_my_app
    type: BuildInfo 
    configuration:
      sourceArtifactory: artifactory_eu
      buildName: helm_chart_myapp
      buildNumber: ${run_number} 