localRepositories:   
  stn-docker-release-local:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    xray:   
      enabled: true
  stn-helm-dev-local:
    type: helm
    repoLayout: simple-default 
    xray:   
      enabled: false
  stn-helm-release-local:
    type: helm
    repoLayout: simple-default 
    xray:   
      enabled: false
remoteRepositories: 
  stn-dockerhub-remote:
    type: docker 
    url: https://registry-1.docker.io/
    dockerApiVersion: V2
    repoLayout: simple-default 
    enableTokenAuthentication: true
    xray:   
      enabled: true
  stn-bintray-remote:
    type: docker
    url: https://docker.bintray.io/
    dockerApiVersion: V2
    repoLayout: simple-default 
    enableTokenAuthentication: true
    xray:   
      enabled: true
  stn-chartcenter-remote:
    type: helm
    url: https://repo.chartcenter.io/
    repoLayout: simple-default 
    xray:   
      enabled: false
virtualRepositories: 
  stn-docker:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    repositories:   
      - stn-docker-release-local
      - stn-dockerhub-remote
      - stn-bintray-remote
    defaultDeploymentRepo: stn-docker-release-local
  stn-helm:
    type: helm
    repoLayout: simple-default 
    repositories:   
      - stn-helm-dev-local
      - stn-helm-release-local
      - stn-chartcenter-remote
    defaultDeploymentRepo: stn-helm-dev-local