localRepositories:   
  saturn-docker-release-local:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    xray:   
      enabled: true
  saturn-helm-dev-local:
    type: helm
    repoLayout: simple-default 
    xray:   
      enabled: false
  saturn-helm-release-local:
    type: helm
    repoLayout: simple-default 
    xray:   
      enabled: false
remoteRepositories: 
  saturn-dockerhub-remote:
    type: docker 
    url: https://registry-1.docker.io/
    dockerApiVersion: V2
    repoLayout: simple-default 
    enableTokenAuthentication: true
    xray:   
      enabled: true
  saturn-bintray-remote:
    type: docker
    url: https://docker.bintray.io/
    dockerApiVersion: V2
    repoLayout: simple-default 
    enableTokenAuthentication: true
    xray:   
      enabled: true
  saturn-chartcenter-remote:
    type: helm
    url: https://repo.chartcenter.io/
    repoLayout: simple-default 
    xray:   
      enabled: false
virtualRepositories: 
  saturn-docker:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    repositories:   
      - saturn-docker-release-local
      - saturn-dockerhub-remote
      - saturn-bintray-remote
    defaultDeploymentRepo: saturn-docker-release-local
  saturn-helm:
    type: helm
    repoLayout: simple-default 
    repositories:   
      - saturn-helm-dev-local
      - saturn-helm-release-local
      - saturn-chartcenter-remote
    defaultDeploymentRepo: saturn-helm-dev-local