Init:
  pipelineName: k8s_project_init
  container:
    registry: saturn-docker.gcp.devopsacc.team:80
    image: jfrog/pipelines-u18node
    tag: 10.21.0-jfrog
    repoSource: saturn-docker
    # repoPromotion1: kaizoku-docker-rc-local
  chart:
    repo: saturn-helm
    name: myapp
    version: 1.0.0
  artifactoryIntegration: artifactory_eu

InitResources:
  gitRepo:
    name: src_code_k8s_app
    gitProvider: yann_github
    path: cyan21/k8s-app
    branches:
      include: demo
    files:
      include: ^chart\/CI\/jfrog\/.+
  gitRepoDocker:
    name: src_dockerfile_base_image_helm
    gitProvider: yann_github
    path: cyan21/k8s-app
    branches:
      include: demo
    files:
      include: ^chart\/CI\/jfrog\/Dockerfile
  gitRepoHelm:
    name: src_code_k8s_helm
    gitProvider: yann_github
    path: cyan21/k8s-app
    branches:
      include: demo
    files:
      include: ^chart\/content\/.+
  buildInfoContainer:
    resourceName: bi_base_image_helm
    name: helm_base_image
  buildInfoHelm:
    resourceName: bi_hc_my_app
    name: helm_chart_myapp
  chart:
    resourceName: hc_my_app
    name: myapp
    version: 1.0.0
    repo: saturn-helm

InitSteps:
  publishHelm:
    name: publish_helm_chart
    path: chart/content/
    lint: true
    autoPublishBuildInfo: true
  dockerBuild:
    name: build_helm_base_image
    dockerFileName: Dockerfile
    dockerFileLocation: chart/CI/jfrog/
  dockerPush:
    name: publish_helm_base_image
    autoPublishBuildInfo: true
    forceXrayScan: false


Chart:
  pipelineName: k8s_bump_helm_chart
  container:
    registry: saturn-docker.saturn-docker.gcp.devopsacc.team:80
    image: jfrog/pipelines-u18node
    tag: 10.21.0-jfrog
    repoSource: saturn-docker
  repo: saturn-helm
  repoPromotion1: saturn-helm-release-local
  name: myapp
  version: 2.0.0
  artifactoryIntegration: artifactory_eu
  k8sIntegration: yann_k8s
  k8sNamespace: saturn

ChartResources:
  gitRepo:
    name: src_code_project
    gitProvider: yann_github
    path: cyan21/k8s-app
    branches:
      include: demo
    files:
      include: ^chart\/content\/.+
  gitRepoHelm:
    name: src_code_helm
    gitProvider: yann_github
    path: cyan21/k8s-app
    branches:
      include: demo
    files:
      include: ^chart\/content\/.+
  chart:
    name: hc_new_myapp
  buildInfo:
    resourceName: bi_hc_new_myapp
    name: k8s_helm_chart
  buildInfoPromoted:
    resourceName: bi_hc_new_myapp_promoted
  fileSpec:
    front:
      name: fs_front_docker_manifest
    back:
      name: fs_back_docker_manifest

ChartSteps:
  publishHelm:
    name: publish_helm_chart
    path: chart/content/
    lint: true
    autoPublishBuildInfo: true
  helmDeploy:
    name: deploy_new_chart
  testing:
    name: test_app
  promotion:
    name: promote_helm_chart
    includeDependencies: false
    status: TEST_OK
    comment: passed non regression test
    copy: false