pipelines:
  - name: frontapp_npm_pipeline
    configuration:
      environmentVariables:
        readOnly:
          art_url: "http://artifactory-eu.soleng-emea-staging.jfrog.team/artifactory"
    steps:
      - name: build_npm_frontend
        type: NpmBuild
        configuration:
          repositoryName: npm
          sourceLocation: front/
          integrations:
            - name: artifactory_eu
          inputResources:
            - name: src_code_frontapp

      - name: npm_package_frontend
        type: Bash
        configuration:
          environmentVariables:
            OFFLINE_MODE: "true"
          inputSteps:
            - name: build_npm_frontend
          integrations:
            - name: artifactory_eu
        execution:
          onStart:
            - echo "Run Unit Testing ..." 
            - if [ $OFFLINE_MODE == "true" ]; then echo "Offline mode turned on";fi
            - ls -la
            - restore_run_files $build_npm_frontend_sourceStateName .
            - cd front
            - ls -la
            - npm run build
          onSuccess:
              - echo ${res_src_code_frontapp_isGitTag}
              - appVersion=`if [[ ${res_src_code_frontapp_isGitTag} == "True" ]]; then echo ${res_src_code_frontapp_gitTagName}; else echo ${res_src_code_frontapp_commitSha}; fi`
              - echo $appVersion 
              - add_pipeline_variables appVersion="${appVersion}"
              - add_pipeline_variables subPath="${res_src_code_frontapp_branchName}/${appVersion}"      
          onComplete:
            - ls -la
            - cd ..
            - add_run_files . $build_npm_frontend_sourceStateName    
            - ls -la

      - name: publish_frontend
        type: NpmPublish
        configuration:
          environmentVariables:
            inputNpmBuildStepName: build_npm_frontend
          repositoryName: npm
          inputSteps:
            - name: npm_package_frontend
          integrations:
            - name: artifactory_eu 

      - name: publish_frontend_buildinfo
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: publish_frontend
          outputResources:
            - name: FrontAppBuildInfo

      - name: scan_npm_frontapp
        type: XrayScan
        configuration:
          failOnScan: false
          inputResources:
            - name: FrontAppBuildInfo
              trigger: true
          outputResources:
            - name: FrontAppBuildInfo_scanned

      - name: promote_build_info_npm_frontapp
        type: PromoteBuild
        configuration:
          targetRepository: app-npm-rc-local
          includeDependencies: false
          status: SANDBOX_OK
          comment: Unit testing and Xray scan passed succesfully
          copy: false
          inputResources:
            - name: FrontAppBuildInfo_scanned
              trigger: true
          outputResources:
            - name: build_info_frontapp_promoted
